swagger: '2.0'
info:
  description: REST API for executing/integrating 5GT placement algorithms
  version: '2'
  title: Placement algorithm API
host: '127.0.0.1:6161'
basePath: /5gt/so/v1
schemes:
  - http
paths:
  /PAComp:
    get:
      summary: Retrieve a list of PA execution requests
      description: Retrieve the list of pending and completed PA requests.
      operationId: p_a_comp_get
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: List of PA requests
          schema:
            type: array
            items:
              $ref: '#/definitions/PAResponse'
      x-swagger-router-controller: swagger_server.controllers.default_controller
    post:
      summary: Request the execution of a placement algorithm.
      description: >-
        Request the execution of a placement algorithm. The caller needs to
        implement a callback function and supply the relevant URI so that the PA
        can post there the result of its execution.-
      operationId: p_a_comp_post
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: PARequest
          description: Placement algorithm request information.
          required: true
          schema:
            $ref: '#/definitions/PARequest'
      responses:
        '200':
          description: PA request successfuly executed
          schema:
            $ref: '#/definitions/PAResponse'
        '201':
          description: PA request created
      x-swagger-router-controller: swagger_server.controllers.default_controller
  '/PAComp/{ReqId}':
    get:
      summary: Retrieve a specific PA request
      description: Retrieve status information about a specific PA request.
      operationId: p_a_comp_req_id_get
      produces:
        - application/json
      parameters:
        - name: ReqId
          in: path
          description: Unique request identifier.
          required: true
          type: string
      responses:
        '200':
          description: PA request information
          schema:
            $ref: '#/definitions/PARequest'
        '404':
          description: PA request not found
      x-swagger-router-controller: swagger_server.controllers.default_controller
definitions:
  coordinate:
    type: object
    required:
      - latitude
      - longitude
    properties:
      longitude:
        type: number
        description: coordinate longitude
      latitude:
        type: number
        description: coordinate latitude
    description: Coordinate expressed in longitude and latitude
    example:
      longitude: 0.8008281904610115
      latitude: 6.027456183070403
  location:
    type: object
    required:
      - radius
    properties:
      center:
        $ref: '#/definitions/coordinate'
      radius:
        type: number
        description: Location ball radius
    description: Location expressed as a ball with a center coordinate and some radius
    example:
      center:
        longitude: 0.8008281904610115
        latitude: 6.027456183070403
      radius: 1.4658129805029452
  NFVIPoP:
    required:
      - capabilities
      - id
    properties:
      id:
        type: string
        description: NFVIPoP id
      location:
        $ref: '#/definitions/location'
      gw_ip_address:
        type: string
        description: Gateway IP addresses
        format: ipv4
      capabilities:
        $ref: '#/definitions/NFVIPoP_capabilities'
      availableCapabilities:
        $ref: '#/definitions/NFVIPoP_availableCapabilities'
      failure_rate:
        type: number
        description: Probability the NFVIPoP fails
      internal_latency:
        type: number
        description: Latency between two VNFs launched inside the NFVIPoP
    example:
      id: id
      internal_latency: 1.2315135367772556
      availableCapabilities:
        ram: 3.616076749251911
        cpu: 9.301444243932576
        bandwidth: 4.145608029883936
        storage: 2.027123023002322
      location:
        center:
          longitude: 0.8008281904610115
          latitude: 6.027456183070403
        radius: 1.4658129805029452
      failure_rate: 7.386281948385884
      gw_ip_address: gw_ip_address
      capabilities:
        ram: 5.637376656633329
        cpu: 5.962133916683182
        bandwidth: 7.061401241503109
        storage: 2.3021358869347655
  LL:
    required:
      - LLid
      - capacity
      - delay
      - destination
      - source
    properties:
      length:
        type: number
      LLid:
        type: string
        description: Logical Link identifier
      capacity:
        $ref: '#/definitions/LL_capacity'
      delay:
        type: number
        description: Logical Link delay
      source:
        $ref: '#/definitions/LL_source'
      destination:
        $ref: '#/definitions/LL_destination'
    example:
      LLid: LLid
      source:
        id: id
        GwIpAddress: GwIpAddress
      length: 1.0246457001441578
      capacity:
        total: 1.4894159098541704
        available: 6.84685269835264
      delay: 7.457744773683766
      destination:
        id: id
        GwIpAddress: GwIpAddress
  VNFCost:
    required:
      - NFVIPoPid
      - cost
      - vnfid
    properties:
      cost:
        type: number
        description: Cost of placing the given VNF at the given NFVIPoP
      vnfid:
        type: string
        description: VNF identifier
      NFVIPoPid:
        type: string
        description: NFVIPoP identifier
    example:
      vnfid: vnfid
      NFVIPoPid: NFVIPoPid
      cost: 1.1730742509559433
  LLCost:
    required:
      - LL
      - cost
    properties:
      cost:
        type: number
        description: Cost of Mbps in the referenced LL
      LL:
        type: string
        description: NFVIPoPs LL identifier
    example:
      LL: LL
      cost: 4.965218492984954
  VLCost:
    required:
      - NFVIPoP
      - cost
    properties:
      cost:
        type: number
        description: Cost of Mbps to use a VL inside the specified NFVIPoP
      NFVIPoP:
        type: string
        description: NFVIPoPs identifier
    example:
      NFVIPoP: NFVIPoP
      cost: 5.025004791520295
  NFVIInfo:
    required:
      - LLs
      - NFVIPoPs
    properties:
      resource_types:
        type: array
        description: Allowed NFVI resource types
        items:
          type: string
      NFVIPoPs:
        type: array
        description: List of NFVIPoPs
        items:
          $ref: '#/definitions/NFVIPoP'
      LLs:
        type: array
        description: Logical links between NFVIPoPs
        items:
          $ref: '#/definitions/LL'
      VNFCosts:
        type: array
        description: Costs to place specific VNFs to specific NFVIPoPs
        items:
          $ref: '#/definitions/VNFCost'
      LLCosts:
        type: array
        description: Cost of using a LL between NFVIPoPs
        items:
          $ref: '#/definitions/LLCost'
      VLCosts:
        type: array
        description: Cost of using a VL inside a NFVIPoP
        items:
          $ref: '#/definitions/VLCost'
    example:
      LLs:
        - LLid: LLid
          source:
            id: id
            GwIpAddress: GwIpAddress
          length: 1.0246457001441578
          capacity:
            total: 1.4894159098541704
            available: 6.84685269835264
          delay: 7.457744773683766
          destination:
            id: id
            GwIpAddress: GwIpAddress
        - LLid: LLid
          source:
            id: id
            GwIpAddress: GwIpAddress
          length: 1.0246457001441578
          capacity:
            total: 1.4894159098541704
            available: 6.84685269835264
          delay: 7.457744773683766
          destination:
            id: id
            GwIpAddress: GwIpAddress
      VLCosts:
        - NFVIPoP: NFVIPoP
          cost: 5.025004791520295
        - NFVIPoP: NFVIPoP
          cost: 5.025004791520295
      LLCosts:
        - LL: LL
          cost: 4.965218492984954
        - LL: LL
          cost: 4.965218492984954
      resource_types:
        - resource_types
        - resource_types
      VNFCosts:
        - vnfid: vnfid
          NFVIPoPid: NFVIPoPid
          cost: 1.1730742509559433
        - vnfid: vnfid
          NFVIPoPid: NFVIPoPid
          cost: 1.1730742509559433
      NFVIPoPs:
        - id: id
          internal_latency: 1.2315135367772556
          availableCapabilities:
            ram: 3.616076749251911
            cpu: 9.301444243932576
            bandwidth: 4.145608029883936
            storage: 2.027123023002322
          location:
            center:
              longitude: 0.8008281904610115
              latitude: 6.027456183070403
            radius: 1.4658129805029452
          failure_rate: 7.386281948385884
          gw_ip_address: gw_ip_address
          capabilities:
            ram: 5.637376656633329
            cpu: 5.962133916683182
            bandwidth: 7.061401241503109
            storage: 2.3021358869347655
        - id: id
          internal_latency: 1.2315135367772556
          availableCapabilities:
            ram: 3.616076749251911
            cpu: 9.301444243932576
            bandwidth: 4.145608029883936
            storage: 2.027123023002322
          location:
            center:
              longitude: 0.8008281904610115
              latitude: 6.027456183070403
            radius: 1.4658129805029452
          failure_rate: 7.386281948385884
          gw_ip_address: gw_ip_address
          capabilities:
            ram: 5.637376656633329
            cpu: 5.962133916683182
            bandwidth: 7.061401241503109
            storage: 2.3021358869347655
  VNF:
    required:
      - VNFid
      - requirements
    properties:
      VNFid:
        type: string
        description: VNF identifier
      CP:
        type: array
        items:
          $ref: '#/definitions/CP'
      instances:
        type: number
        description: Number of instances of this VNF to deploy
      requirements:
        $ref: '#/definitions/VNF_requirements'
      failure_rate:
        type: number
        description: Probability that a VNF instance of this type fails.
      processing_latency:
        type: number
        description: >-
          Latency for a VNF instance with the specific characteristics to
          process a service request.
    description: Information about a specific VNF.
    example:
      processing_latency: 1.284659006116532
      failure_rate: 6.965117697638846
      VNFid: VNFid
      CP:
        - cpId: cpId
          VNFLink:
            id: id
            latency: 6.683562403749608
            traversal_probability: 9.369310271410669
            required_capacity: 9.965781217890562
        - cpId: cpId
          VNFLink:
            id: id
            latency: 6.683562403749608
            traversal_probability: 9.369310271410669
            required_capacity: 9.965781217890562
      instances: 8.762042012749001
      requirements:
        ram: 6.438423552598547
        cpu: 9.018348186070783
        storage: 3.5571952270680973
  VNFLink:
    required:
      - id
    properties:
      id:
        type: string
        description: Unique Virtual Link identifier
      required_capacity:
        type: number
        description: >-
          Maximum volume of traffic/s expected between these two VNFs and along
          this direction, and thus required capacity for the underlying VL
          between the NFVIPoPs that the two VNFs will be placed.
      traversal_probability:
        type: number
        description: >-
          Probability that a request traverses this link. This allows for
          branchesin the VNFFG (e.g., for load  balancing, etc.). If this
          parameter is omitted, it is assumed equal to 1.
      latency:
        type: number
        description: Maximum latency in ms
    description: An edge between two VNFs in the VNFFG.
    example:
      id: id
      latency: 6.683562403749608
      traversal_probability: 9.369310271410669
      required_capacity: 9.965781217890562
  NetworkService:
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: Network service identifier
      name:
        type: string
        description: Name of the network service
      VNFs:
        type: array
        description: VNFs composing the service
        items:
          $ref: '#/definitions/VNF'
      VNFLinks:
        type: array
        description: Edges of the VNFFG
        items:
          $ref: '#/definitions/VNFLink'
      SAP:
        type: array
        items:
          $ref: '#/definitions/SAP'
      max_latency:
        type: number
        description: End-to-end latency constraint.
      target_availability:
        type: number
        description: Target service availability.
      max_cost:
        type: number
        description: Cost/budget constraint
    description: Description of a network service.
    example:
      id: id
      max_cost: 6.878052220127876
      SAP:
        - location:
            center:
              longitude: 0.8008281904610115
              latitude: 6.027456183070403
            radius: 1.4658129805029452
          CPid: CPid
          VNFLink: VNFLink
        - location:
            center:
              longitude: 0.8008281904610115
              latitude: 6.027456183070403
            radius: 1.4658129805029452
          CPid: CPid
          VNFLink: VNFLink
      max_latency: 2.8841621266687802
      name: name
      target_availability: 6.778324963048013
      VNFLinks:
        - id: id
          latency: 6.683562403749608
          traversal_probability: 9.369310271410669
          required_capacity: 9.965781217890562
        - id: id
          latency: 6.683562403749608
          traversal_probability: 9.369310271410669
          required_capacity: 9.965781217890562
      VNFs:
        - processing_latency: 1.284659006116532
          failure_rate: 6.965117697638846
          VNFid: VNFid
          CP:
            - cpId: cpId
              VNFLink:
                id: id
                latency: 6.683562403749608
                traversal_probability: 9.369310271410669
                required_capacity: 9.965781217890562
            - cpId: cpId
              VNFLink:
                id: id
                latency: 6.683562403749608
                traversal_probability: 9.369310271410669
                required_capacity: 9.965781217890562
          instances: 8.762042012749001
          requirements:
            ram: 6.438423552598547
            cpu: 9.018348186070783
            storage: 3.5571952270680973
        - processing_latency: 1.284659006116532
          failure_rate: 6.965117697638846
          VNFid: VNFid
          CP:
            - cpId: cpId
              VNFLink:
                id: id
                latency: 6.683562403749608
                traversal_probability: 9.369310271410669
                required_capacity: 9.965781217890562
            - cpId: cpId
              VNFLink:
                id: id
                latency: 6.683562403749608
                traversal_probability: 9.369310271410669
                required_capacity: 9.965781217890562
          instances: 8.762042012749001
          requirements:
            ram: 6.438423552598547
            cpu: 9.018348186070783
            storage: 3.5571952270680973
  CP:
    required:
      - cpId
    properties:
      cpId:
        type: string
      VNFLink:
        $ref: '#/definitions/VNFLink'
    description: Information about a specific CP.
    example:
      cpId: cpId
      VNFLink:
        id: id
        latency: 6.683562403749608
        traversal_probability: 9.369310271410669
        required_capacity: 9.965781217890562
  SAP:
    properties:
      CPid:
        type: string
        description: Id of the associated CP
      VNFLink:
        type: string
        description: ID of the associated VNFLink
      location:
        $ref: '#/definitions/location'
    description: Information about a specific SAP.
    example:
      location:
        center:
          longitude: 0.8008281904610115
          latitude: 6.027456183070403
        radius: 1.4658129805029452
      CPid: CPid
      VNFLink: VNFLink
  PARequest:
    type: object
    required:
      - ReqId
      - callback
    properties:
      ReqId:
        type: string
        description: Unique request identifier
      nfvi:
        $ref: '#/definitions/NFVIInfo'
      nsd:
        $ref: '#/definitions/NetworkService'
      callback:
        type: string
        format: URL
        description: Callback URL
    example:
      nsd:
        id: id
        max_cost: 6.878052220127876
        SAP:
          - location:
              center:
                longitude: 0.8008281904610115
                latitude: 6.027456183070403
              radius: 1.4658129805029452
            CPid: CPid
            VNFLink: VNFLink
          - location:
              center:
                longitude: 0.8008281904610115
                latitude: 6.027456183070403
              radius: 1.4658129805029452
            CPid: CPid
            VNFLink: VNFLink
        max_latency: 2.8841621266687802
        name: name
        target_availability: 6.778324963048013
        VNFLinks:
          - id: id
            latency: 6.683562403749608
            traversal_probability: 9.369310271410669
            required_capacity: 9.965781217890562
          - id: id
            latency: 6.683562403749608
            traversal_probability: 9.369310271410669
            required_capacity: 9.965781217890562
        VNFs:
          - processing_latency: 1.284659006116532
            failure_rate: 6.965117697638846
            VNFid: VNFid
            CP:
              - cpId: cpId
                VNFLink:
                  id: id
                  latency: 6.683562403749608
                  traversal_probability: 9.369310271410669
                  required_capacity: 9.965781217890562
              - cpId: cpId
                VNFLink:
                  id: id
                  latency: 6.683562403749608
                  traversal_probability: 9.369310271410669
                  required_capacity: 9.965781217890562
            instances: 8.762042012749001
            requirements:
              ram: 6.438423552598547
              cpu: 9.018348186070783
              storage: 3.5571952270680973
          - processing_latency: 1.284659006116532
            failure_rate: 6.965117697638846
            VNFid: VNFid
            CP:
              - cpId: cpId
                VNFLink:
                  id: id
                  latency: 6.683562403749608
                  traversal_probability: 9.369310271410669
                  required_capacity: 9.965781217890562
              - cpId: cpId
                VNFLink:
                  id: id
                  latency: 6.683562403749608
                  traversal_probability: 9.369310271410669
                  required_capacity: 9.965781217890562
            instances: 8.762042012749001
            requirements:
              ram: 6.438423552598547
              cpu: 9.018348186070783
              storage: 3.5571952270680973
      ReqId: ReqId
      callback: callback
      nfvi:
        LLs:
          - LLid: LLid
            source:
              id: id
              GwIpAddress: GwIpAddress
            length: 1.0246457001441578
            capacity:
              total: 1.4894159098541704
              available: 6.84685269835264
            delay: 7.457744773683766
            destination:
              id: id
              GwIpAddress: GwIpAddress
          - LLid: LLid
            source:
              id: id
              GwIpAddress: GwIpAddress
            length: 1.0246457001441578
            capacity:
              total: 1.4894159098541704
              available: 6.84685269835264
            delay: 7.457744773683766
            destination:
              id: id
              GwIpAddress: GwIpAddress
        VLCosts:
          - NFVIPoP: NFVIPoP
            cost: 5.025004791520295
          - NFVIPoP: NFVIPoP
            cost: 5.025004791520295
        LLCosts:
          - LL: LL
            cost: 4.965218492984954
          - LL: LL
            cost: 4.965218492984954
        resource_types:
          - resource_types
          - resource_types
        VNFCosts:
          - vnfid: vnfid
            NFVIPoPid: NFVIPoPid
            cost: 1.1730742509559433
          - vnfid: vnfid
            NFVIPoPid: NFVIPoPid
            cost: 1.1730742509559433
        NFVIPoPs:
          - id: id
            internal_latency: 1.2315135367772556
            availableCapabilities:
              ram: 3.616076749251911
              cpu: 9.301444243932576
              bandwidth: 4.145608029883936
              storage: 2.027123023002322
            location:
              center:
                longitude: 0.8008281904610115
                latitude: 6.027456183070403
              radius: 1.4658129805029452
            failure_rate: 7.386281948385884
            gw_ip_address: gw_ip_address
            capabilities:
              ram: 5.637376656633329
              cpu: 5.962133916683182
              bandwidth: 7.061401241503109
              storage: 2.3021358869347655
          - id: id
            internal_latency: 1.2315135367772556
            availableCapabilities:
              ram: 3.616076749251911
              cpu: 9.301444243932576
              bandwidth: 4.145608029883936
              storage: 2.027123023002322
            location:
              center:
                longitude: 0.8008281904610115
                latitude: 6.027456183070403
              radius: 1.4658129805029452
            failure_rate: 7.386281948385884
            gw_ip_address: gw_ip_address
            capabilities:
              ram: 5.637376656633329
              cpu: 5.962133916683182
              bandwidth: 7.061401241503109
              storage: 2.3021358869347655
  PAResponse:
    type: object
    required:
      - worked
    properties:
      worked:
        type: boolean
        description: Specifies if the PA worked and found a solution
      result:
        type: string
        description: Description of the PA result
      usedNFVIPops:
        type: array
        description: Array of all used NFVI PoPs with mapped VNFs
        items:
          $ref: '#/definitions/PAResponse_usedNFVIPops'
      usedLLs:
        type: array
        description: >-
          Array of all used LL between NFVIPoPs by the mapped Network Service
          VLs
        items:
          $ref: '#/definitions/PAResponse_usedLLs'
      usedVLs:
        type: array
        description: Array of all used VL inside NFVIPoPs by the mapped Network Service VLs
        items:
          $ref: '#/definitions/PAResponse_usedVLs'
      totalLatency:
        type: number
        description: Network Sewrvice latency after placement
      totalCost:
        type: number
        description: cost of mapping the Network Service expressed in euros
    description: Response to a PA request
    example:
      result: result
      usedNFVIPops:
        - NFVIPoPID: NFVIPoPID
          mappedVNFs:
            - mappedVNFs
            - mappedVNFs
        - NFVIPoPID: NFVIPoPID
          mappedVNFs:
            - mappedVNFs
            - mappedVNFs
      totalCost: 6.027456183070403
      usedVLs:
        - mappedVLs:
            - mappedVLs
            - mappedVLs
          NFVIPoP: NFVIPoP
        - mappedVLs:
            - mappedVLs
            - mappedVLs
          NFVIPoP: NFVIPoP
      totalLatency: 0.8008281904610115
      usedLLs:
        - mappedVLs:
            - mappedVLs
            - mappedVLs
          LLID: LLID
        - mappedVLs:
            - mappedVLs
            - mappedVLs
          LLID: LLID
      worked: true
  NFVIPoP_capabilities:
    required:
      - cpu
      - ram
      - storage
    properties:
      cpu:
        type: number
        description: NFVIPoP CPU capacity
      ram:
        type: number
        description: RAM capacity (in MB)
      storage:
        type: number
        description: storage capacity (in MB)
      bandwidth:
        type: number
        description: link capacity (in Mbps)
      mec:
        type: boolean
        description: MEC capability
    description: Capacity for different resources of the NFVIPoP
    example:
      ram: 5.637376656633329
      cpu: 5.962133916683182
      bandwidth: 7.061401241503109
      storage: 2.3021358869347655
      mec: true
  NFVIPoP_availableCapabilities:
    required:
      - cpu
      - ram
      - storage
    properties:
      cpu:
        type: number
        description: NFVIPoP CPU capacity
      ram:
        type: number
        description: RAM capacity (in MB)
      storage:
        type: number
        description: storage capacity (in MB)
      bandwidth:
        type: number
        description: link capacity (in Mbps)
    description: Available capacity for different resources of the NFVIPoP
    example:
      ram: 3.616076749251911
      cpu: 9.301444243932576
      bandwidth: 4.145608029883936
      storage: 2.027123023002322
  LL_capacity:
    properties:
      total:
        type: number
        description: Total link capacity (Mbps)
      available:
        type: number
        description: Available link capacity (Mbps)
    description: Logical Link capacity
    example:
      total: 1.4894159098541704
      available: 6.84685269835264
  LL_source:
    required:
      - GwIpAddress
      - id
    properties:
      id:
        type: string
        description: Source NFVIPoP id
      GwIpAddress:
        type: string
        format: ipv4
        description: Endpoint IP address
    description: Source NFVIPoP
    example:
      id: id
      GwIpAddress: GwIpAddress
  LL_destination:
    required:
      - GwIpAddress
      - id
    properties:
      id:
        type: string
        description: Destination NFVIPoP id
      GwIpAddress:
        type: string
        format: ipv4
        description: Endpoint IP address
    description: Destination NFVIPoP
    example:
      id: id
      GwIpAddress: GwIpAddress
  VNF_requirements:
    required:
      - cpu
      - ram
      - storage
    properties:
      cpu:
        type: number
        description: CPU requirements
      ram:
        type: number
        description: Memory requirements (in MB)
      storage:
        type: number
        description: Storage requirements (in MB)
      mec:
        type: boolean
        description: Requirement that MEC is supported
    description: VNF processing and other requirements
    example:
      ram: 6.438423552598547
      cpu: 9.018348186070783
      storage: 3.5571952270680973
      mec: false
  PAResponse_usedNFVIPops:
    properties:
      NFVIPoPID:
        type: string
        description: NFVI PoP ID
      mappedVNFs:
        type: array
        description: all VNFs mapped in this NFVI PoP
        items:
          type: string
          description: VNF ID
    description: NFVIPoP with mapped VNFs
    example:
      NFVIPoPID: NFVIPoPID
      mappedVNFs:
        - mappedVNFs
        - mappedVNFs
  PAResponse_usedLLs:
    properties:
      LLID:
        type: string
        description: LL ID
      mappedVLs:
        type: array
        description: all VLs mapped in this LL between NFVI PoP
        items:
          type: string
          description: VL ID
    description: LLs with mapped VLs
    example:
      mappedVLs:
        - mappedVLs
        - mappedVLs
      LLID: LLID
  PAResponse_usedVLs:
    properties:
      NFVIPoP:
        type: string
        description: NFVIPoP ID
      mappedVLs:
        type: array
        description: all VLs mapped in this LL between NFVI PoP
        items:
          type: string
          description: VL ID
    description: Intra NFVIPoP VLs with mapped VLs on top of them
    example:
      mappedVLs:
        - mappedVLs
        - mappedVLs
      NFVIPoP: NFVIPoP